language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

script:
  #- black --check --exclude SRC /home/travis/build/dc5212/swe1-app/myvenv
  #- flake8 --exclude=migrations .
  # - pytest
  - coverage run --source=mysite,polls, manage.py test

after_script:
  - python -m coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "testSite"
  env: "dj-env-3"
  bucket_name: "elasticbeanstalk-us-east-1-855318216650"
  on:
    branch: main 
