language: python
python:
  - "3.8"
before_install:
  - pip install 'urllib3<2.0'  
install:
  - pip install -r requirements.txt

script:
  - black --check . --exclude=eb-virt
  - flake8 --exclude=migrations .
  - pytest
  - coverage run ./manage.py test blogs

after_script:
  - python -m coveralls


deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "testSite"
  env: "dj-env-3"
  bucket_name: "elasticbeanstalk-us-east-1-855318216650"
  on:
    branch: main 
